version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
    networks:
      - appnet
  frontend:
    build: ./frontend
    container_name: frontend_streamlit
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
